spring:
  application:
    name: dubbo-provider
server:
  port: 9002


dubbo:
  application:
    name: dubbo-provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://127.0.0.1:2181
  consumer:
    timeout: 5000